import { jsPDF } from "jspdf";

const PAGE_WIDTH = 210;
const PAGE_MARGIN = 14;

function colorFromScore(score) {
  if (score >= 80) return [59, 220, 151];
  if (score >= 60) return [255, 190, 99];
  return [255, 107, 99];
}

function sectionHeader(doc, title, y) {
  doc.setFillColor(233, 242, 247);
  doc.rect(PAGE_MARGIN, y - 4, PAGE_WIDTH - PAGE_MARGIN * 2, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 47, 67);
  doc.text(title, PAGE_MARGIN, y);
  return y + 8;
}

function formatCurrency(value) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

function createCanvas(width, height) {
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, height);
  return { canvas, ctx };
}

function createHorizontalBarChartImage({
  title,
  subtitle,
  items,
  scaleMax = 100,
  formatter = (item) => `${item.value}`,
}) {
  const { canvas, ctx } = createCanvas(920, 420);
  const left = 250;
  const right = 90;
  const top = 108;
  const chartWidth = canvas.width - left - right;
  const rowGap = 60;
  const barHeight = 18;

  ctx.fillStyle = "#112031";
  ctx.font = "700 30px Arial";
  ctx.fillText(title, 38, 46);
  ctx.fillStyle = "#5d7085";
  ctx.font = "400 16px Arial";
  ctx.fillText(subtitle, 38, 74);

  [0, 0.25, 0.5, 0.75, 1].forEach((tick) => {
    const x = left + chartWidth * tick;
    ctx.strokeStyle = "#e5edf3";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, top - 26);
    ctx.lineTo(x, top + rowGap * (items.length - 1) + 24);
    ctx.stroke();

    ctx.fillStyle = "#6f8397";
    ctx.font = "400 13px Arial";
    ctx.fillText(String(Math.round(scaleMax * tick)), x - 10, top - 34);
  });

  items.forEach((item, index) => {
    const y = top + index * rowGap;
    const width = chartWidth * (Math.min(item.value, scaleMax) / scaleMax);
    const color = item.color || [52, 201, 219];

    ctx.fillStyle = "#16283e";
    ctx.font = "600 18px Arial";
    ctx.fillText(item.label, 38, y + 4);

    ctx.fillStyle = "#eef4f8";
    ctx.fillRect(left, y - 14, chartWidth, barHeight);

    ctx.fillStyle = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 0.92)`;
    ctx.fillRect(left, y - 14, width, barHeight);

    ctx.fillStyle = "#112031";
    ctx.font = "700 17px Arial";
    ctx.fillText(formatter(item), left + chartWidth + 18, y + 2);
  });

  return canvas.toDataURL("image/png");
}

function drawHeader(doc, timestamp, score, recommendationLabel) {
  doc.setFillColor(7, 20, 35);
  doc.rect(0, 0, 210, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(245, 248, 250);
  doc.text("RouteWise AI", 14, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(160, 181, 198);
  doc.text("Logistics Decision Report", 14, 26);
  doc.text(timestamp, 14, 33);

  const rgb = colorFromScore(score);
  doc.setFillColor(...rgb);
  doc.roundedRect(147, 8, 49, 23, 4, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(21);
  doc.setTextColor(255, 255, 255);
  doc.text(String(score), 171.5, 20, { align: "center" });
  doc.setFontSize(8);
  doc.text(recommendationLabel, 171.5, 27, { align: "center" });
}

function drawFooter(doc, pageLabel) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(116, 132, 148);
  doc.text(`Generated by RouteWise AI · ${pageLabel}`, 105, 286, {
    align: "center",
  });
}

export function generateReportPdf(report) {
  const doc = new jsPDF();
  const timestamp = new Date(report.generated_at).toLocaleString();

  const signalChart = createHorizontalBarChartImage({
    title: "Decision signal scores",
    subtitle: "How the selected route performed across the live scoring inputs",
    items: [
      { label: "ETA reliability", value: report.signals.eta_reliability, color: [52, 201, 219] },
      { label: "Cost efficiency", value: report.signals.cost_efficiency, color: [255, 141, 76] },
      { label: "Carbon efficiency", value: report.signals.carbon_efficiency, color: [59, 220, 151] },
      { label: "Disruption resilience", value: report.signals.disruption_resilience, color: [90, 160, 255] },
      { label: "Customs readiness", value: report.signals.customs_readiness, color: [255, 190, 99] },
    ],
  });

  const routeScoreChart = createHorizontalBarChartImage({
    title: "Route option scores",
    subtitle: "Weighted result across ETA, cost, and CO2 for the current disruption mix",
    items: report.routes.map((route) => ({
      label: route.title,
      value: route.score,
      color: colorFromScore(route.score),
    })),
  });

  const etaChart = createHorizontalBarChartImage({
    title: "Customs-aware ETA comparison",
    subtitle: "Full delivery horizon including disruption and clearance buffers",
    scaleMax: Math.max(...report.routes.map((route) => route.eta_hours), 10),
    formatter: (item) => `${item.value} h`,
    items: report.routes.map((route) => ({
      label: route.title,
      value: route.eta_hours,
      color: [52, 201, 219],
    })),
  });

  const carbonChart = createHorizontalBarChartImage({
    title: "CO2 per route",
    subtitle: "Projected carbon load for the same shipment across all options",
    scaleMax: Math.max(...report.routes.map((route) => route.co2_kg), 100),
    formatter: (item) => `${item.value} kg`,
    items: report.routes.map((route) => ({
      label: route.title,
      value: route.co2_kg,
      color: [59, 220, 151],
    })),
  });

  drawHeader(doc, timestamp, report.recommendation_score, report.recommendation.label);

  let y = 52;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(30, 47, 67);
  doc.text("Dispatch Summary", 14, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 88, 106);
  [
    `Scenario: ${report.scenario_name}`,
    `Corridor: ${report.corridor}`,
    `Cargo: ${report.cargo_tons}T`,
    `Priority: ${report.priority}`,
    `Duration: ${report.duration_label}`,
    `Recommendation: ${report.recommendation.label}`,
  ].forEach((line) => {
    doc.text(line, 14, y);
    y += 6;
  });

  y += 4;
  y = sectionHeader(doc, "Selected Route", y);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(24, 38, 55);
  doc.text(report.selected_route.title, 14, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 88, 106);
  const selectedLines = [
    `Mode: ${report.selected_route.mode}`,
    `ETA: ${report.selected_route.eta_hours} hours`,
    `Projected cost: ${formatCurrency(report.selected_route.cost_inr)}`,
    `Projected CO2: ${report.selected_route.co2_kg} kg`,
    `Customs buffer: ${report.selected_route.customs_hours} hours`,
  ];
  selectedLines.forEach((line) => {
    doc.text(line, 14, y);
    y += 6;
  });

  y += 3;
  y = sectionHeader(doc, "Route Matrix", y);

  doc.setFillColor(241, 246, 249);
  doc.rect(14, y - 4, 182, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(30, 47, 67);
  doc.text("Route", 16, y);
  doc.text("ETA", 97, y);
  doc.text("Cost", 117, y);
  doc.text("CO2", 151, y);
  doc.text("Score", 181, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  report.routes.forEach((route) => {
    doc.setTextColor(55, 74, 92);
    doc.text(route.title, 16, y);
    doc.text(`${route.eta_hours}h`, 97, y);
    doc.text(formatCurrency(route.cost_inr), 117, y);
    doc.text(`${route.co2_kg}kg`, 151, y);
    doc.text(String(route.score), 181, y);
    y += 6;
  });

  y += 4;
  y = sectionHeader(doc, "Alerts", y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  if (!report.alerts.length) {
    doc.setTextColor(71, 88, 106);
    doc.text("No live alerts were raised for this simulation window.", 14, y);
    y += 7;
  } else {
    report.alerts.forEach((alert) => {
      const rgb =
        alert.severity === "high"
          ? [255, 107, 99]
          : alert.severity === "medium"
            ? [255, 190, 99]
            : [59, 220, 151];
      doc.setFillColor(...rgb);
      doc.circle(17, y - 1.5, 1.7, "F");
      doc.setTextColor(71, 88, 106);
      const wrapped = doc.splitTextToSize(`${alert.message} [${alert.time}]`, 170);
      doc.text(wrapped, 22, y);
      y += wrapped.length * 5.5;
    });
  }

  y += 3;
  y = sectionHeader(doc, "Decision Note", y);
  doc.setFillColor(234, 244, 240);
  doc.rect(14, y, 182, 25, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(24, 38, 55);
  doc.text("Operator recommendation", 18, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 88, 106);
  const note = `${report.recommendation.message} ${report.llm_brief}`;
  doc.text(doc.splitTextToSize(note, 168), 18, y + 15);

  drawFooter(doc, "Page 1 of 2");

  doc.addPage();
  drawHeader(doc, timestamp, report.recommendation_score, report.recommendation.label);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 47, 67);
  doc.text("Decision Graphs", 14, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 88, 106);
  doc.text("Visual comparisons for the final route recommendation", 14, 59);

  doc.addImage(signalChart, "PNG", 14, 68, 182, 48);
  doc.addImage(routeScoreChart, "PNG", 14, 121, 182, 48);
  doc.addImage(etaChart, "PNG", 14, 174, 182, 48);
  doc.addImage(carbonChart, "PNG", 14, 227, 182, 48);

  drawFooter(doc, "Page 2 of 2");

  doc.save(`RouteWise_AI_Report_${report.scenario_name.replace(/\s+/g, "_")}.pdf`);
}
